accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout')
]

djangoblog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('about/', views.about)
]

posts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list),
    path('<slug:slug>/', views.post_detail, name='post_detail'),
]

accounts/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[0:70]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/posts/')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('/posts/')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('/accounts/login/')

djangoblog/views.py
from django.http import HttpResponse
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')

posts/views.py
from django.shortcuts import render
from .models import Post


def post_list(request):
    posts = Post.objects.all().order_by('date')
    return render(request, 'posts/post_list.html', {'posts': posts})


def post_detail(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, 'posts/post_detail.html', {'post': post})

accounts/templates/accounts/layout/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% load static %}
    <link rel="stylesheet" href="{% static "posts/css/bootstrap.min.css" %}">

    <title>Django Blog</title>
</head>
<body class="container mt-5">
{% block content %}

{% endblock content %}
</body>
</html>

accounts/templates/accounts/login.html
{% extends "./layout/base.html" %}
{% load static %}

{% block content %}
    <h1>Log In</h1>
    <form action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Log In">
    </form>
    <div>
        <br>
    <a href="/accounts/signup/" class="btn btn-primary">Sign Up</a>

    </div>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends "./layout/base.html" %}
{% load static %}

{% block content %}
    <h1>Signup</h1>
    <form action="/accounts/signup/" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Signup">
    </form>

    <div>
        <br>
    <a href="/accounts/login/" class="btn btn-primary">Login</a>

    </div>


{% endblock content %}

posts/templates/posts/layout/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% load static %}
    <link rel="stylesheet" href="{% static "posts/css/bootstrap.min.css" %}">

    <title>Django Blog</title>
</head>
<body class="container mt-5">
<nav class="mb-3">
    {% if user.is_authenticated %}
        <form action="{% url 'accounts:logout' %}" method="post">
            {% csrf_token %}
            <button class="btn btn-primary btn-sm" type="submit">Log Out</button>
        </form>
    {% endif %}
</nav>
{% block content %}

{% endblock content %}
</body>
</html>

posts/templates/posts/post_detail.html
{% extends "./layout/base.html" %}
{% load static %}

{% block content %}

    <div class="card mb-4" style="width: 40rem">
        <img src="{% static 'posts/images/'|add:post.slug|add:'.jpeg' %}" class="card-img-top">
        <div class="card-body">
            <h3 class="card-title">{{ post.title }}</h3>
            <h6 class="card-subtitle mb-2 text-muted">{{ post.slug }}</h6>
            <p class="card-text">{{ post.body }}</p>
        </div>
    </div>

{% endblock content %}

posts/templates/posts/post_list.html
{% extends "./layout/base.html" %}
{% load static %}

{% block content %}
    {% for post in posts %}
        <div class="card mb-4" style="width: 40rem">
            <img src="{% static 'posts/images/'|add:post.slug|add:'.jpeg' %}" class="card-img-top">
            <div class="card-body">
                <h3 class="card-title">{{ post.title }}</h3>
                <h6 class="card-subtitle mb-2 text-muted">{{ post.slug }}</h6>
                <p class="card-text">{{ post.snippet }}...</p>
                <a href="{% url 'post_detail' post.slug %}" class="btn btn-primary">Read More</a>
            
            
            </div>
        </div>
    {% endfor %}
{% endblock content %}

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>The About Page</title>
    <h1>About Page!</h1>
    <h3>Here you can learn all kinds of things about Django!</h3>
</head>
<body>

</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>The Home Page</title>
    <h1>Home Page!</h1>
    <h3>Hi there, thanks for visiting the home page!</h3>
</head>
<body>

</body>
</html>

templates/posts/post_list2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Posts</title>
</head>
<body>
<h1>Posts List</h1>

{% for post in posts %}
    <h2>{{ post.title }}</h2>
    <h3>{{ post.snippet }}...</h3>
    <h4>{{ post.slug }}</h4>
    <hr>
{% endfor %}

</body>
</html>